################################################################
#
# Pipeline pipeline_velocyto.py configuration file
#
# This pipeline.yml file lists some configuration options that you
# need to set before running the pipeline.
#
################################################################

# genome ID
# e.g. hg38 or mm10
genome: hg38
genome_dir: /ifs/mirror/genomes/index/

# Location of the single cell directory
sc_dir: '/ifs/devel/annajb/scRNA/single-cell/'

# Project name
projectname: ''

# Copyright statement
copyright: Cribbs Group, Botnar Research Centre (2019)

# Location of the data. 0 for current working directory, 1 for data.dir, other= defined path
data: 0

# Provide a reference geneset (suffix= ".gtf.gz")
# Geneset should be located in working directory
geneset: geneset_all.gtf.gz


################################################################
## merge options
################################################################
merge:
  # input pattern
  # For example, if your files are called:
  #    CLLP80-S1-1-L001.fastq.1.gz
  #    CLLP80-S1-1-L001.fastq.2.gz
  #    CLLP80-S1-1-L002.fastq.1.gz
  #    CLLP80-S1-1-L002.fastq.2.gz
  # and you want to create files/ folder starting with:
  #    CLLP80-S1-1
  # i.e. merge lanes
  # choose the following input and output patterns:
  #
  # pattern_input=(.*)-(S\d)-(\d)-(L\d+)
  # pattern_output=\1-\2-\3
  # Note that the file extension will be added by the pipeline. The
  # pattern must not include this.

  # hgmm_100_S1_L001_001.fastq.1.gz
  # hgmm_100_S1_L001_001.fastq.2.gz
  # hgmm_100_S1_L002_001.fastq.1.gz
  # hgmm_100_S1_L002_001.fastq.2.gz

  # pattern_input: (\S+)_(\d+)_(S\d)_(L\d+)_(\d+)
  # pattern_output: \1_\2_\3
  # to create:
  # hgmm_100_S1

  pattern_input: (\S+)_(\d+)_(S\d)_(L\d+)
  pattern_output: \1_\2_\3

#########################
# Barcode correction and annotation
#########################

# Salmon alevin

salmon:
  # Length of k-mer for indexing.
  kmer: 31

  # Number of threads that can be used by alevin to perform the quantification
  threads: 10

  # Library type must be specified.
  # ISR recommended for DropSeq and 10xV2 technology
  librarytype: ISR

  # Whether to run alevin
  alevin: 1

  sctechnology: chromium

  # Whether to use chromium defualts (16 CB + 10 UMI)
  default_barcodes: 1

  # Otherwise these values used
  barcode_length: 7
  umi_length: 9
  end: 5

#########################
# Mapping 
#########################

star:

  # Whether to run star mapping
  run: 1

  # The number of threads for genome generation
  threads: 32

  memory: unlimited

  # The RAM limit 
  RAM_limit: 87779818880
  
